name: Desktop Build

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: |
          git config --global core.autocrlf false
          chmod +x gradlew

      - name: Build with Gradle
        id: gradle-build
        run: |
          ./gradlew :desktop:build
          ./gradlew --stop

      - name: Upload desktop build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: desktop-windows-build
          path: desktop/build/
